# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgis
  encoding: utf8
  database: lithium_poc_development
  username: postgres
  host: localhost
  pool: 5
  port: 5432
  password: secretcloset
